### ISSUE TITLE
Support declarative use of a layout

### ISSUE THREAD

**Issue by fabslab** [bartve/dot-view#1]
People creating template files should be able to declare in the file which layout they want to use for a partial. Then we can parse that instead of defining the layout in the code where people who create the templates may not have access.

We just need to choose a syntax for the declaration.

**Comment by bartve** [comment]
I may not understand you correctly, but doesn't doT already allow this? Check http://olado.github.io/doT/index.html and then the tab 'partials'. Or do you mean the inclusion of actual template files?

**Comment by bartve** [comment]
Oops, didn't mean to close this, wrong button.

**Comment by fabslab** [comment]
I don't think so? Right now to create a layout for a template you have to use 
`view.layout(new View('/layouts', 'layout.dot', {title: 'My title'}));` as in your readme. 
If the person creating the templates can't do this because they are creating a theme for example, they need another way to declare the layout template.

**Comment by fabslab** [comment]
To be clearer, say I have this layout file `default.dot` like in your readme example:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>{{=it.title}}</title>
    </head>
    <body>
        <div>{{#def._content}}</div>
    </body>
</html>
```

If I decide I want to use that as my layout for a template `page.dot` I could do something like:

``` html
{{< default }}
<div>Some content!</div>
```

Where I have created the syntax `{{< layoutName }}` for declaring the layout template to use.
It would be equivalent to doing this in code:

``` javascript
var pageView = new View('/tpl/path', 'page.dot');
pageView.layout(new View('/layouts', 'default.dot', {title: 'My title'}));
var html = pageView.render();
```

**Comment by bartve** [comment]
Clear! Thanks for the elaborate explanation. As `dot-view` is merely a wrapper for `doT`, so I feel a bit uncomfortable adding new template syntax as these templates would stop working with native `doT` then. Isn't this something that should be done in the compiler function of  `doT` itself?

Otherwise I can only include things in the template for `dot-view` to pick up that don't hurt the normal doT template rendering function, like: `{{var layout = 'layout.dot';}}` at the top of a sub-template or even something as simple as  `{{'layout:layout.dot';}}` or a dummy define `{{##def.layout:layout.dot#}}`.

I like the last option best as this way no unused garbage ends up in the compiled `doT` template function.

**Comment by fabslab** [comment]
Yeah that's true, it would either have to be done in doT itself or the new syntax would have to seem like a comment to doT so that it has no side effect to existing template files.

**Comment by fabslab** [comment]
I would be interested in a solution using your last suggestion too.

**Comment by bartve** [comment]
I wanted to use the comment options too, but as far as I could see `doT` has no comment syntax of its own and javascript comment `{{/* layout.dot */}}` results in a literal `{{}}` being added to the template output because it isn't picked up by any of the regular expressions.

**Comment by fabslab** [comment]
I'm not sure if it still applies but I saw this
https://github.com/olado/doT/issues/68

**Comment by bartve** [comment]
Thanks, that link got me trying some more variations as `{{/* test */}}` didn't work, 
but `{{ /*test*/ }}` and even `{{ /*test*/}}` work! How does `{{ /* layout:layout.dot */ }}` look?

**Comment by fabslab** [comment]
Interesting find. That looks good enough!

**Comment by bartve** [comment]
I'm busy this weekend, but I'll add this somewhere next week.
I've already built a regex `/\{\{\s+\/\*\s*layout:(.+\S+)\s*\*\/\s*\}\}/` which should do the trick.

`doT` allows you to override the replacement delimiters {{...}}, but for now as a first implementation I'm going to assume {{ and }} are used. I can always make the regex above configurable just the way `doT` does.

**Comment by fabslab** [comment]
Cool, I think something like your other suggestion would be fine too by the way if you prefer that: `{{##def._layout:layout.dot#}}`

**Comment by bartve** [comment]
The cool thing is the regular expression to pick up the layout will be configurable just like the `doT` tags, so you can use any tag syntax you like. I'll default to `{{ /* layout:layout.dot */ }}` as this method is 100% safe.

Edit: Hmm, on the other hand `{{##def._layout:layout.dot#}}` would be compatible with the way the template content is placed in the layout with `{{#def._content}}`.

Update: I will also include `{{#def.include('path/to/sub-template.dot')}}` to include sub-templates from a template file rather than from code.

**Comment by bartve** [comment]
See release 0.3.0
